language: ruby
before_install:
  - rake --version
  - sudo apt-get update -qq
  - sudo apt-get install -qq libpcap-dev
  # Uncomment when we have fewer shipping msftidy warnings.
  # Merge committers will still be checking, just not autofailing.
  # See https://dev.metasploit.com/redmine/issues/8498
  # - ln -sf ../../tools/dev/pre-commit-hook.rb ./.git/hooks/post-merge
  # - ls -la ./.git/hooks
  # - ./.git/hooks/post-merge
before_script:
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake --version
  - bundle exec rake db:create
  - bundle exec rake db:migrate

rvm:
  #- '1.8.7'
  - '1.9.3'

notifications:
  irc: "irc.freenode.org#msfnotify"

git:
  depth: 5
